import typescriptEslint from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';
import eslintPluginImport from 'eslint-plugin-import';
import eslintPluginN from 'eslint-plugin-n';

export default [
  {
    files: ['src/**/*.ts'],
    ignores: ['dist/', 'node_modules/', 'coverage/', 'data/', '*.js', '*.d.ts'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parser: typescriptParser,
      parserOptions: {
        project: './tsconfig.json',
      },
      globals: {
        node: true,
        es2022: true,
        jest: true,
      },
    },
    plugins: {
      '@typescript-eslint': typescriptEslint,
      import: eslintPluginImport,
      n: eslintPluginN,
    },
    rules: {
      // TypeScript Rules - Keep only essential ones
      '@typescript-eslint/no-unused-vars': 'off', // Disable unused vars check
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-inferrable-types': 'off',
      '@typescript-eslint/no-var-requires': 'off', // Allow require statements
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/prefer-optional-chain': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/await-thenable': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',

      // General Rules - Keep minimal
      'no-console': 'off',
      'no-debugger': 'off',
      'no-alert': 'off',
      'no-eval': 'off',
      'no-implied-eval': 'off',
      'no-new-func': 'off',
      'no-script-url': 'off',
      'no-void': 'off',
      'no-with': 'off',
      strict: 'off',
      'no-undef': 'off',
      'no-unused-vars': 'off',
      'no-redeclare': 'off',
      'no-dupe-class-members': 'off',
      'no-loss-of-precision': 'off',
      'no-promise-executor-return': 'off',
      'no-unreachable-loop': 'off',
      'no-useless-backreference': 'off',
      'require-atomic-updates': 'off',

      // Best Practices - Disable problematic ones
      'array-callback-return': 'off',
      'block-scoped-var': 'off',
      complexity: 'off',
      'consistent-return': 'off',
      curly: 'off', // Disable curly brace requirement
      'default-case': 'off',
      'default-case-last': 'off',
      'dot-notation': 'off',
      eqeqeq: 'off',
      'grouped-accessor-pairs': 'off',
      'guard-for-in': 'off',
      'max-classes-per-file': 'off',
      'max-depth': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-nested-callbacks': 'off',
      'max-params': 'off',
      'no-caller': 'off',
      'no-case-declarations': 'off', // Allow declarations in case blocks
      'no-constructor-return': 'off',
      'no-else-return': 'off',
      'no-empty-function': 'off',
      'no-empty-pattern': 'off',
      'no-extend-native': 'off',
      'no-extra-bind': 'off',
      'no-extra-label': 'off',
      'no-fallthrough': 'off',
      'no-global-assign': 'off',
      'no-implicit-coercion': 'off',
      'no-implicit-globals': 'off',
      'no-invalid-this': 'off',
      'no-iterator': 'off',
      'no-labels': 'off',
      'no-lone-blocks': 'off',
      'no-loop-func': 'off',
      'no-magic-numbers': 'off',
      'no-multi-assign': 'off',
      'no-multi-str': 'off',
      'no-new': 'off',
      'no-new-wrappers': 'off',
      'no-octal': 'off',
      'no-octal-escape': 'off',
      'no-param-reassign': 'off',
      'no-proto': 'off',
      'no-return-assign': 'off',
      'no-return-await': 'off', // Allow return await
      'no-self-assign': 'off',
      'no-self-compare': 'off',
      'no-sequences': 'off',
      'no-throw-literal': 'off',
      'no-unmodified-loop-condition': 'off',
      'no-unused-expressions': 'off',
      'no-useless-call': 'off',
      'no-useless-catch': 'off',
      'no-useless-concat': 'off', // Allow string concatenation
      'no-useless-escape': 'off', // Allow escape characters
      'no-useless-return': 'off',
      'prefer-const': 'off',
      'prefer-promise-reject-errors': 'off',
      'prefer-regex-literals': 'off',
      radix: 'off',
      'require-await': 'off',
      'vars-on-top': 'off',
      'wrap-iife': 'off',
      yoda: 'off',

      // Stylistic Rules - All off
      camelcase: 'off',
      'capitalized-comments': 'off',
      'consistent-this': 'off',
      'func-name-matching': 'off',
      'func-names': 'off',
      'func-style': 'off',
      'id-denylist': 'off',
      'id-length': 'off',
      'max-statements-per-line': 'off',
      'new-cap': 'off',
      'no-array-constructor': 'off',
      'no-bitwise': 'off',
      'no-continue': 'off',
      'no-inline-comments': 'off',
      'no-lonely-if': 'off',
      'no-negated-condition': 'off',
      'no-nested-ternary': 'off',
      'no-new-object': 'off',
      'no-plusplus': 'off',
      'no-restricted-syntax': 'off',
      'no-ternary': 'off',
      'no-underscore-dangle': 'off',
      'no-unneeded-ternary': 'off',
      'one-var': 'off',
      'operator-assignment': 'off',
      'prefer-exponentiation-operator': 'off', // Allow Math.pow
      'prefer-object-spread': 'off',
      'spaced-comment': 'off',

      // ES6+ Rules - All off
      'arrow-body-style': 'off',
      'arrow-parens': 'off',
      'arrow-spacing': 'off',
      'constructor-super': 'off',
      'generator-star-spacing': 'off',
      'no-class-assign': 'off',
      'no-confusing-arrow': 'off',
      'no-const-assign': 'off',
      'no-duplicate-imports': 'off',
      'no-new-symbol': 'off',
      'no-restricted-exports': 'off',
      'no-restricted-imports': 'off',
      'no-this-before-super': 'off',
      'no-useless-computed-key': 'off',
      'no-useless-constructor': 'off',
      'no-useless-rename': 'off',
      'no-var': 'off',
      'object-shorthand': 'off',
      'prefer-arrow-callback': 'off',
      'prefer-destructuring': 'off',
      'prefer-numeric-literals': 'off',
      'prefer-rest-params': 'off',
      'prefer-spread': 'off',
      'prefer-template': 'off',
      'require-yield': 'off',
      'rest-spread-spacing': 'off',
      'sort-imports': 'off',
      'symbol-description': 'off',
      'template-curly-spacing': 'off',
      'yield-star-spacing': 'off',

      // Import Rules - All off
      'import/order': 'off',
      'import/first': 'off',
      'import/no-duplicates': 'off',
      'import/no-unresolved': 'off',
      'import/no-cycle': 'off',
      'import/no-self-import': 'off',
      'import/no-useless-path-segments': 'off',
      'import/newline-after-import': 'off',
      'import/no-absolute-path': 'off',
      'import/no-dynamic-require': 'off',
      'import/no-webpack-loader-syntax': 'off',

      // Node.js Rules - All off
      'n/no-deprecated-api': 'off',
      'n/no-extraneous-import': 'off',
      'n/no-extraneous-require': 'off',
      'n/no-missing-import': 'off',
      'n/no-missing-require': 'off',
      'n/no-unpublished-import': 'off',
      'n/no-unpublished-require': 'off',
      'n/no-unsupported-features/es-syntax': 'off',
      'n/prefer-global/buffer': 'off',
      'n/prefer-global/console': 'off',
      'n/prefer-global/process': 'off',
      'n/prefer-global/url-search-params': 'off',
      'n/prefer-global/url': 'off',
      'n/prefer-promises/dns': 'off',
      'n/prefer-promises/fs': 'off',
    },
    settings: {
      'import/resolver': {
        typescript: {
          alwaysTryTypes: true,
          project: './tsconfig.json',
        },
      },
      node: {
        tryExtensions: ['.js', '.json', '.ts'],
      },
    },
  },
  {
    files: ['**/*.test.ts', '**/*.spec.ts', '**/__tests__/**/*.ts'],
    languageOptions: {
      globals: { jest: true },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/unbound-method': 'off',
      'max-lines-per-function': 'off',
      'max-lines': 'off',
      'no-magic-numbers': 'off',
      'id-denylist': 'off',
    },
  },
  {
    files: ['src/types/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/ban-types': 'off',
      'max-lines': 'off',
    },
  },
  {
    files: ['src/config.ts'],
    rules: {
      'no-magic-numbers': 'off',
    },
  },
  {
    files: ['*.js'],
    languageOptions: {
      globals: { node: true, commonjs: true },
    },
    rules: {
      '@typescript-eslint/no-var-requires': 'off',
    },
  },
];